-- https://programmers.co.kr/learn/courses/30/lessons/59044
-- 1번과 비슷한 문제, LIMIT 추가

-- 본 문제의 집합 수식 => ANIMAL_INS － ANIMAL_OUTS (ANIMAL_INS에 대한 ANIMAL_OUTS의 차집합)

SELECT ANIMAL_INS.NAME, ANIMAL_INS.DATETIME
  FROM ANIMAL_INS
  LEFT OUTER JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
  WHERE ANIMAL_OUTS.ANIMAL_ID IS NULL
  ORDER BY ANIMAL_INS.DATETIME
  LIMIT 3
