-- https://programmers.co.kr/learn/courses/30/lessons/59045
-- RIGHT (OUTER) JOIN 문법 문제

-- 본 문제의 집합 수식 => ANIMAL_INS ∩ ANIMAL_OUTS ＋ ANIMAL_OUTS

SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
  FROM ANIMAL_INS
  RIGHT OUTER JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
  WHERE ANIMAL_INS.SEX_UPON_INTAKE != ANIMAL_OUTS.SEX_UPON_OUTCOME
  ORDER BY ANIMAL_OUTS.ANIMAL_ID
